version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18
      - echo Installing source code dependencies...
      - yarn install

  # pre_build:
  #   commands:
  #     - echo Running tests...
  #     - npm test

  build:
    commands:
      - echo Building the React app...
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'build/'


cache:
  paths:
    - 'node_modules/**/*'